camps = [
    "Amoy Quee Camp",
    "Bedok Camp I",
    "Bedok Camp II",
    "Clementi Camp",
    "Depot Road Camp",
    "Dieppe Barracks",
    "Gombak Base",
    "Hendon Camp",
    "Jurong Camp I",
    "Jurong Camp II",
    "Kaki Bukit Camp",
    "Keat Hong Camp",
    "Khatib Camp",
    "Mowbray Camp",
    "Kranji Camp II",
    "Kranji Camp III",
    "Ladang Camp",
    "Rocky Hill Camp",
    "Maju Camp",
    "Mandai Hill Camp",
    "Nee Soon Camp",
    "Nee Soon Driclad Centre",
    "Pasir Laba Camp",
    "Pasir Ris Camp",
    "Rifle Range Road Camp",
    "SAFTI Military Institute",
    "Selarang Camp",
    "Seletar Camp",
    "Sembawang Camp",
    "Stagmont Camp",
    "Sungei Gedong Camp",
]
